matrix:
  include:

    # OSX continuous release build
    - env: RIPES_PLATFORM='mac'
      os: osx
      osx_image: xcode11
      language: c++
      addons:
        apt:
          packages:
            - tree

    # Windows continuous release build
    - os: windows
      language: cpp
      env:
        - RIPES_PLATFORM: 'windows'

    # Xenial continuous release build
    - env: RIPES_PLATFORM='linux'
      os: linux
      dist: xenial
      sudo: required
      language: c++
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.11.0-xenial'
              key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x10C56D0DE9977759'
            - ubuntu-toolchain-r-test
          packages:
            - qt511-meta-minimal
            - qt511svg
            - qt511charts-no-lgpl
            - libc6-dev
            - g++-8
            - tree
            - mesa-common-dev

     # Bionic unit test build
    - env: RIPES_PLATFORM='linux_test'
      os: linux
      dist: bionic
      sudo: required
      language: c++
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt-5.11.0-bionic'
              key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x10C56D0DE9977759'
            - ubuntu-toolchain-r-test
          packages:
            - qt511-meta-minimal
            - qt511svg
            - qt511charts-no-lgpl
            - libc6-dev
            - g++-8
            - tree
            - mesa-common-dev

before_install:
    - source ${TRAVIS_BUILD_DIR}/scripts/${RIPES_PLATFORM}/before_install.sh

script:
    - source ${TRAVIS_BUILD_DIR}/scripts/${RIPES_PLATFORM}/travisbuild.sh

after_success:
    - source ${TRAVIS_BUILD_DIR}/scripts/${RIPES_PLATFORM}/after_success.sh

branches:
 except:
   - # Do not build tags that we create when we upload to GitHub Releases
   - /^(?i:continuous)/
